homeassistant:
  # Name of the location where Home Assistant is running
  name: Pornolounge
  # Location required to calculate the time the sun rises and sets
  latitude: deine Position
  longitude: deine Position
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: deine Hoehe
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  customize: !include customize.yaml
# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config: 

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
#sensor:
#  platform: yr
  
# Text to speech
tts:
  platform: google
  
group: !include groups.yaml
automation: !include_dir_merge_list automation/
sensor: !include_dir_merge_list sensor/
input_select: !include_dir_merge_named input_select/
input_slider: !include_dir_merge_named input_slider/
input_boolean: !include_dir_merge_named input_boolean/
switch: !include_dir_merge_list switch/
script: !include_dir_merge_named scripts/

   






